services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    # build:
    #   context: ./backend
    image: ghcr.io/ajaypds/todo-backend:latest
    container_name: todo-backend

    depends_on:
      - postgres

    environment:
      DB_URL: "${DB_URL}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"

    ports:
      - "8080:8080"
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    # build:
    #   context: ./frontend
    image: ghcr.io/ajaypds/todo-frontend:latest
    container_name: todo-frontend

    depends_on:
      - backend

    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  postgres_data:
