spring:
  application:
    name: todo

  datasource:
    url: jdbc:postgresql://localhost:5432/todoapp
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

jwt:
  secret: KBDVKDFVGUBUYNDINDUY33433472R67HBJHDBJBHBKB
  expiration: 900000
  refresh-expiration: 604800000

server:
  port: 8080
